name: TicTacToeSW_HW

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Завантажити код

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2  # Налаштувати Visual Studio
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore client/client.sln

      - name: gtest
        run:  nuget install gtest
       


      - name: Build solution
        run: |
          msbuild client/client.sln /p:Configuration=Release /p:Platform="x64" /p:OutputPath="client/build"

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: client/x64/Release/*.exe

  build_arduino:
    runs-on: ubuntu-latest  # Використовуємо Linux для компіляції Arduino

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Завантажити код

      - name: Set up Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xzf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli config init

      - name: Add Arduino package URL
        run: |
          arduino-cli config set board_manager.additional_urls https://downloads.arduino.cc/packages/package_index.json

      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Arduino Sketch for Uno
        run: |
          mkdir -p build  # Переконатися, що директорія для збірки існує
          arduino-cli compile --fqbn arduino:avr:uno --output-dir build server/server.ino

      - name: Upload Arduino binaries
        uses: actions/upload-artifact@v4  # Оновлено до v4
        with:
          name: arduino-hex
          path: build/*.hex  # Шлях до .hex файлів
  test:
    runs-on: windows-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Завантажити код

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore client/client.sln

      - name: Run unit tests
        run: |
          msbuild client/client.sln /p:Configuration=Release /p:Platform="x64" /p:RunTests=true > test_results.log; 
          if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.log
