name: nazarkok

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '16.0'  # Задайте версію Visual Studio, яку ви використовуєте

      - name: Restore NuGet packages
        run: nuget restore client/client.sln  # Заміна на ім'я вашого рішення

      - name: Build solution
        run: msbuild client/client.sln /p:Configuration=Release  # Заміна на ім'я вашого рішення
      - name: Move executable to build folder
        run: |
          mkdir build
          move /Y "client/x64/Debug/*.exe" build/  # Заміна на фактичний шлях до вашого .exe файлу

