name: TicTacToeSW_HW

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Завантажити код

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2  # Налаштувати Visual Studio
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore client/client.sln

      - name: Build solution
        run: |
          msbuild client/client.sln /p:Configuration=Release /p:Platform="x64" /p:OutputPath="client/build"

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: client/x64/Release/*.exe

  build_arduino:
    runs-on: ubuntu-latest  # Використовуємо Linux для компіляції Arduino

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Завантажити код

      - name: Set up Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xzf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli config init

      - name: Add Arduino package URL
        run: |
          arduino-cli config set board_manager.additional_urls https://downloads.arduino.cc/packages/package_index.json

      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile Arduino Sketch for Uno
        run: |
          mkdir -p build  # Переконатися, що директорія для збірки існує
          arduino-cli compile --fqbn arduino:avr:uno --output-dir build server/server.ino

      - name: Upload Arduino binaries
        uses: actions/upload-artifact@v4  # Оновлено до v4
        with:
          name: arduino-hex
          path: build/*.hex  # Шлях до .hex файлів

  build-and-test:
    runs-on: windows-latest
    name: Build and Test C++/CLI App

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0'  # або іншу версію, яка тобі потрібна

    - name: Restore NuGet packages
      run: nuget restore client/client.sln

    - name: Build solution
      run: |
        msbuild client/client.sln /p:Configuration=Release /p:Platform="x64" /p:OutputPath="client/build" /verbosity:minimal

    - name: Run tests
      run: |
        vstest.console.exe client/build/TestsProject.dll --logger:trx --resultsDirectory:./tests/results/cppcli

    - name: Save Test Results
      run: |
        $testResultPath = "./tests/results/cppcli/cppcli-app-test-report.trx"
        Write-Host "Test report saved to: $testResultPath"

    - name: Post Test Report
      uses: bibipkins/dotnet-test-reporter@v1.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Test Report'
        results-path: ./tests/results/cppcli/*.trx

    - name: Upload Test Results Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cppcli-app-test-reports
        path: ./tests/results/cppcli/*