name: nazarkok

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '16.0'  # Задайте версію Visual Studio, яку ви використовуєте

      - name: Restore NuGet packages
        run: nuget restore client/client.sln  # Заміна на ім'я вашого рішення

      - name: Build solution
        run: msbuild client/client.sln /p:Configuration=Release  # Заміна на ім'я вашого рішення


  collect_artifacts:
    needs: [build]  # Виконується після завершення обох завдань
    runs-on: ubuntu-latest

    steps:
      # Checkout code (якщо необхідно)
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload both WinForms and Arduino artifacts
      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: winforms-executable
          path: |
            client/x64/Release/client.exe  # WinForms .exe
          retention-days: 5  # Зберігання артефактів на 5 днів


