name: nazarkok

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore client/client.sln

      - name: Build solution
        run: msbuild client/client.sln /p:Configuration=Release

  collect_artifacts:
    needs: [build]
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: winforms-executable
          path: |
            D:\a\nazarkok\nazarkok\client\x64\Release\client.exe  # Вказуйте повний шлях
          retention-days: 5
