name: nazarkok

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated version

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2  # Updated version
        with:
          vs-version: '16.0'

      - name: Restore NuGet packages
        run: nuget restore client/client.sln

      - name: Build solution
        run: msbuild client/client.sln /p:Configuration=Release

              # Upload Arduino binaries
      - name: Upload Arduino binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: build/*.exe  # Arduino .hex файли

  # Job для компіляції Arduino Uno
  build_arduino:
    runs-on: ubuntu-latest  # Використовуємо Linux для збірки Arduino

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Arduino CLI
      - name: Set up Arduino CLI
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz
          tar -xzf arduino-cli_latest_Linux_64bit.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli config init

      # Add Arduino package URL
      - name: Add Arduino Uno package URL
        run: |
          arduino-cli config set board_manager.additional_urls https://downloads.arduino.cc/packages/package_index.json

      # Install Arduino core for Arduino Uno
      - name: Install Arduino core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      # Compile Arduino Sketch for Arduino Uno
      - name: Compile Arduino Sketch for Uno
        run: |
          mkdir -p build  # Ensure the build directory exists
          arduino-cli compile --fqbn arduino:avr:uno --output-dir build server/server.ino

      # Upload Arduino binaries
      - name: Upload Arduino binaries
        uses: actions/upload-artifact@v3
        with:
          name: arduino-binaries
          path: build/*.hex  # Arduino .hex файли

  collect_artifacts:
    needs: [build]
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated version

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: winforms-executable
          path: client/x64/Release/client.exe  # Ensure this path is correct
          retention-days: 5
