name:  nazarkok

on:
  push:
    branches:
      - develop
      - feature/develop/task2
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Visual Studio
        uses: actions/setup-msbuild@v1
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore client.sln

      - name: Build solution
        run: msbuild clinet.sln /p:Configuration=Release


